### ISSUE TITLE
wikidata2018_09_11.hdt.gz down

### ISSUE THREAD

**Issue by RomainClaret** [PhilippChr/CONVEX#1]
Hello,

Sadly, http://gaia.infor.uva.es/hdt/wikidata/wikidata2018_09_11.hdt.gz, is down :( I contacted them but no response yet.

I was wondering if it would be possible to share that file from your side? Based on the information provided here: http://www.rdfhdt.org/datasets/ I expect it to be about 30gb.

For example, we could use http://academictorrents.com or anything.

Best regards

**Comment by PhilippChr** [comment]
Hello,

Unfortunately we can not upload the file for the public, since we are not the originators.
Also, the link will surely be live again soon. In the meanwhile, we can provide a copy of the file on request. So please contact me (pchristm@mmci.uni-saarland.de) in that case.

Regards,
Philipp
