### ISSUE TITLE
A question about ConvQuestion 

### ISSUE THREAD

**Issue by 2213500360** [PhilippChr/CONVEX#10]
Hello, I have carefully looked at your ConvQuestion dataset and found that not all the question's answer can be found in the wikidata. 

For example, the fifth dialogue in the books domain data of the training set contains the question: "what character joins Harry Potter after being saved by him? "Although I find the answer Hermione Granger in Harry Potter's characters, I didn't find the relevant information of "being saved by".
The sixth dialogue in the tv_series domain data of the training set contains the question: " What's the name of the two copies? " I didn't find any information about the problem.
In addition to the above two, there are other unanswerable questions
Is this because wikidata has been updated to delete the required information, or does the dataset itself contain unanswerable questions? Or the answer can be found in wikidata, but I didn't find it?
THX

**Comment by PhilippChr** [comment]
Hello,

thanks for your question!
Yes, you will not find answering facts for all questions in the current Wikidata-version.

This was actually done intentionally, for two reasons:
1) We did not want to restrict the users to the knowledge graph, and rather aimed for natural questions. 
Users were allowed to use the whole web to generate questions and answers.
2) Wikidata is steadily growing, and while this information is not there now, it could be added in the future. 
E.g. Wikidata only had information on married partner (via spouse predicate) in the beginning, but now it also
has the unmarried partner relation (see Leonardo DiCaprio for example https://www.wikidata.org/wiki/Q38111).
Facts about book content could also be added. E.g. for Elizabeth Bennet, which is a fictional character in a book,
you can find her love interest(s) in Wikidata now (https://www.wikidata.org/wiki/Q2223341).

Thus, there might be questions that are not answerable using Wikidata **now**,
but can probably be answered in the future.

Regards,
Philipp
