### ISSUE TITLE
Node Embedding

### ISSUE THREAD

**Issue by SRL94** [PhilippChr/CONVEX#14]
Hi, in Equation (2), CONVEX initialises the word embeddings of a question by using word2vec but how does CONVEX initialise node embeddings?

**Comment by PhilippChr** [comment]
Hello,

within each node you would have a phrase (label of the KB-item).
So node embeddings are the averaged word embeddings.

We do not materialize these initial node embeddings, 
but directly compute the matching similarity with the question:
https://github.com/PhilippChr/CONVEX/blob/260d02933748abc74b0fc1d317ad46181960c2ce/convex.py#L226-L236

This function implements Equation (1), using cosine similarity.

Hope this answers your question.

Regards,
Philipp

**Comment by SRL94** [comment]
How about unknow words?

**Comment by PhilippChr** [comment]
Unknown words would get a 0 vector. A similarity of 0 is returned.
https://github.com/PhilippChr/CONVEX/blob/260d02933748abc74b0fc1d317ad46181960c2ce/library/glove_similarity.py#L34-L35
