### ISSUE TITLE
Where to download the dataset

### ISSUE THREAD

**Issue by SRL94** [PhilippChr/CONVEX#15]
Hi,

I have downloaded the Wikidata2018_09_11. Where could I download the ConvQuestions question-answering pairs? I clicked the buttons shown in the image but they did not work.
<img width="789" alt="Screen Shot 2022-01-26 at 1 02 16 pm" src="https://user-images.githubusercontent.com/44760001/151106849-883853e2-b657-4650-a5f5-68a226ceee6b.png">

**Comment by SRL94** [comment]
Also, are ConvQuestions simple or complex questions?

**Comment by PhilippChr** [comment]
Hi,

this is strange. The download from https://convex.mpi-inf.mpg.de works for me.
Could you try the following links please (maybe also with wget)?
http://qa.mpi-inf.mpg.de/convex/ConvQuestions_train.zip
http://qa.mpi-inf.mpg.de/convex/ConvQuestions_dev.zip
http://qa.mpi-inf.mpg.de/convex/ConvQuestions_test.zip

The dataset consists of conversations with 5 turns each. Such conversations have a complete initial question,
and 4 incomplete follow-up questions, which require information from the ongoing conversational context.
The information need itself can be quite complex (you can see some examples on the homepage).

If you are interested in complete questions, you can take a look at the completed questions in the seed dataset:
http://qa.mpi-inf.mpg.de/convex/ConvQuestionsSeed.json
Completed questions are collected together with the incomplete ones, and some require 
aggregation, chain joins, star joins, comparison; and there are also existential questions (asking for Yes/No).

Regards,
Philipp

**Comment by SRL94** [comment]
Thanks, Philipp. The urls work for me.
