### ISSUE TITLE
Count Questions

### ISSUE THREAD

**Issue by SRL94** [PhilippChr/CONVEX#16]
Hi, it seems that the model only selected one entity from the knowledge graph as the answer. How does it handle count questions, e.g. "Led Zeppelin had how many band members?"

**Comment by PhilippChr** [comment]
Hi,
CONVEX does not have a specific mechanism to handle count questions.
Note, that for many such questions the information is there in Wikidata though.
E.g. Game of Thrones (https://www.wikidata.org/wiki/Q23572) has the number of seasons
and number of episodes.

Regards,
Philipp

**Comment by SRL94** [comment]
> Hi, CONVEX does not have a specific mechanism to handle count questions. Note, that for many such questions the information is there in Wikidata though. E.g. Game of Thrones (https://www.wikidata.org/wiki/Q23572) has the number of seasons and number of episodes.
> 
> Regards, Philipp

Thanks, Philipp. You always have a swift reply.

**Comment by SRL94** [comment]
Hi Phillipp,

Does CONVEX only work for questions whose answers are entities? That is, CONVEX cannot handle count, comparison and "Yes or No" questions in the ConvQuestions dataset.

Best regards
Sirui

**Comment by PhilippChr** [comment]
Hi Sirui,

CONVEX does not have specific mechanisms to deal with such complexities.
If the information is there in the data (which can often be the case for count questions as indicated above),
it can get the answer. But there are no explicit mechanisms for aggregations or comparisons.
For existential question (Yes/No), we employ a proxy to always answer with "Yes".

Regards,
Philipp
