### ISSUE TITLE
About requirements

### ISSUE THREAD

**Issue by Bigchen8013** [PhilippChr/CONVEX#18]
Hi，

Are you running on linux? I can't install the HDT package on Windows, do you have a solution? In addition, when I use python -m spacy download en_vectors_web_lg, the download is not successful, there is no response for a long time or the requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)) is prompted.

**Comment by Bigchen8013** [comment]
To install HDT, I refer to issue 5, but still no success！

**Comment by PhilippChr** [comment]
Hi, 
Yes I am running the code on a linux machine.
When using Windows, maybe you could try using Anaconda?

Regards,
Philipp

**Comment by Bigchen8013** [comment]
Hi,
On Windows I use Anaconda, but I still can't install the HDT package.
When I use the command `python -m spacy download en_vectors_web_lg` on linux, there is no response for a long time.

**Comment by PhilippChr** [comment]
Hi,
Very hard for me to comment on this, unfortunately.
You could see if other spacy-models can be downloaded.
Maybe there are some firewall rules that don't allow the download?

Regards,
Philipp

**Comment by Bigchen8013** [comment]
Hi Philipp,

I know why the download failed`python -m spacy download en_vectors_web_lg`. Because the name of the version after spacy v3 is not called “en_vectors_web_lg”, please refer to the [link](https://cloud.tencent.com/developer/ask/sof/356935) for details.

When I use the command `nohup python convex.py > myfirstrun.log 2>&1 &` to run, myfirstrun.log shows `nohup: ignoring input
Predicate Bitmap in 1 min 10 sec 219 ms 91 us
Count predicates in 8 min 33 sec 703 ms 892 us
Count Objects in 4 min 44 sec 624 ms 990 us Max was: 543914579
Bitmap in 17 sec 807 ms 689 us
Bitmap bits: 7230127313 Ones: 1190479283
Object references in 39 min 58 sec 710 ms 519 us
Sort lists in 54 min 4 sec 727 ms 339 us
Index generated in 1 hour 48 min 49 sec 793 ms 689 us
What is the name of the writer of The Secret Garden?
What is the name of the writer of The Secret Garden?
What is the name of the writer of The Secret Garden?
...
What is the name of the writer of The Secret Garden?
What is the name of the writer of The Secret Garden?
`, and it stays at the first question, do you know what's going on?

Regards,
Bigchen

**Comment by PhilippChr** [comment]
Hi, 

this seems to be the same problem as in issue #6:
Wikidata is a large KB, and therefore CONVEX comes with quite some RAM requirements.

Regards,
Philipp

**Comment by PhilippChr** [comment]
Hi,

Did you manage to fix this problem?
If the RAM requirement for the KB is a problem, I refer to our WSDM 2022 paper,
for which an API for accessing Wikidata is publicly available: https://clocq.mpi-inf.mpg.de.

Regards,
Philipp

**Comment by Bigchen8013** [comment]
Hi,
Philipp


Thank you very much for your reply. I have found the specific reason, it is because my linux cannot access the API of wikidata.
Thank you very much for your reference.


Regards,
Bigchen






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PhilippChr/CONVEX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月21日(星期一) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PhilippChr/CONVEX] About requirements (Issue #18)





 
Hi,
 
Did you manage to fix this problem?
 If the RAM requirement for the KB is a problem, I refer to our WSDM 2022 paper,
 for which an API for accessing Wikidata is publicly available: https://clocq.mpi-inf.mpg.de.
 
Regards,
 Philipp
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
