### ISSUE TITLE
Predicate index

### ISSUE THREAD

**Issue by SRL94** [PhilippChr/CONVEX#20]
Hi,

Why there is a "predicate_index"? Thank you!
```
if not qualifier_predicate_nodes.get(qualifier_statement['qualifier_predicate']['id']):
	# the qualifier_predicate did not occur yet => index 0 and new entry
	qualifier_predicate_nodes[qualifier_statement['qualifier_predicate']['id']] = 1
	predicate_index = 0
else:
	# the qualifier_predicate already occured => fetch the next index available and increase the saved one
	predicate_index = qualifier_predicate_nodes[qualifier_statement['qualifier_predicate']['id']]
	qualifier_predicate_nodes[qualifier_statement['qualifier_predicate']['id']] += 1
```

**Comment by PhilippChr** [comment]
Hi,

the KB has many instances of the same predicate.
E.g. almost every entity in Wikidata has a fact with the "instance-of" (~type) predicate.

In the graph representation, we do not want to merge all these instances of the same predicate within one node.
With such merging, important information would be lost.

Two example KB-facts:
The Last Unicorn, instance of, movie
The Unicorn, instance of, fictional character

If both "instance-of" nodes would be merged in a graph information is lost.
It is not clear any more, whether The Last Unicorn is a movie or a fictional character.

Therefore, we give each occurrence of a predicate a unique ID.

Regards,
Philipp

**Comment by SRL94** [comment]
Thanks Philipp!
