### ISSUE TITLE
requests.get('https://tagme.d4science.org/tagme/tag‘）error

### ISSUE THREAD

**Issue by lihuiliullh** [PhilippChr/CONVEX#22]
Hi, I run the code, and found that the program always got error in the follow line. Do you know what happens?

![image](https://user-images.githubusercontent.com/53407011/190930702-7b0648b9-a1fb-42ae-8552-6c0fc1c06f6d.png)

**Comment by PhilippChr** [comment]
Hi, 
did you enter your tagme-token in the config?
Regards,
Philipp

**Comment by lihuiliullh** [comment]
Thx. I think the service of TagMe is shut down. Do you know how to solve this problem?

**Comment by PhilippChr** [comment]
Not really, maybe you could contact them directly.
In case you just need a NERD tool, you could also use:
https://clocq.mpi-inf.mpg.de
