### ISSUE TITLE
May I know what data is stored in these files?

### ISSUE THREAD

**Issue by lihuiliullh** [PhilippChr/CONVEX#23]
May I know what data is stored in these files?

![image](https://user-images.githubusercontent.com/53407011/191056936-8cbeebea-ae8b-4644-aa74-e5ff248ef792.png)

**Comment by PhilippChr** [comment]
Hi,
identifier_predicates: set of predicates mapping to external IDs
label dict: dictionary to map from Wikidata ID to label
predicate frequencies: dictionary storing KB prior for predicates
entity frequencies: dictionary storing KB prior for entities
statements dict: dictionary storing KB facts

**Comment by lihuiliullh** [comment]
why should all the entities and predicates in identifier_predicates be ignored in the code?

**Comment by PhilippChr** [comment]
This only affects predicates.
Consider some example facts with identifier predicates on Christopher Nolan (https://www.wikidata.org/wiki/Q25191) below.

Such facts are not required in most QA use cases, and are adding noise to the whole process.
I cannot imagine someone asking for the "Bibliothèque nationale de France ID" of Nolan.

![image](https://user-images.githubusercontent.com/24608689/191684385-5dff2cbe-7390-41a1-a8bc-0dda43f7344e.png)
