### ISSUE TITLE
what is 'qualifiers'?

### ISSUE THREAD

**Issue by lihuiliullh** [PhilippChr/CONVEX#24]
May I know what is qualifiers? Can you give an example of it?

![image](https://user-images.githubusercontent.com/53407011/191396605-86417fd9-f15b-4a0a-b58b-1b25ffadf749.png)

**Comment by PhilippChr** [comment]
Qualifiers are used in Wikidata (similar concepts exist in other KGs), and extend the standard triple structure to store contextual information on a fact, like the date in time, the character of a cast member, a series ordinal and similar.

"A fact is a <subject, predicate, object> triple, that is optionally augmented by <qualifier predicate, qualifier object> pairs which specify context information for the main triple. For example, <2018 FIFA World Cup Final, participating team, France national football team; location, Luzhniki Stadium; point in time, 15 July 2018> is such a fact, where the first three items constitute the main triple, and the last four make up two qualifier predicate-qualifier object tuples." (from https://arxiv.org/pdf/2108.08597.pdf)

**Comment by lihuiliullh** [comment]
Thanks.
