### ISSUE TITLE
pip install hdt does not work in python 3.7 macOS

### ISSUE THREAD

**Issue by jingjing-unilu** [PhilippChr/CONVEX#5]
when I try "pip install hdt" in my terminal, I encounter the problem("pybind11" has been installed): 
```
Collecting hdt
  Using cached hdt-2.3.tar.gz (229 kB)
Collecting pybind11==2.2.4
  Using cached pybind11-2.2.4-py2.py3-none-any.whl (145 kB)
Building wheels for collected packages: hdt
  Building wheel for hdt (setup.py) ... error
  ERROR: Command errored out with exit status 1:
command: /usr/local/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/dc/dd3sxplx0h97kmd_xhrqx2h40000gn/T/pip-install-zbfuwsf7/hdt/setup.py'"'"'; __file__='"'"'/private/var/folders/dc/dd3sxplx0h97kmd_xhrqx2h40000gn/T/pip-install-zbfuwsf7/hdt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/dc/dd3sxplx0h97kmd_xhrqx2h40000gn/T/pip-wheel-73maa_ez
       cwd: /private/var/folders/dc/dd3sxplx0h97kmd_xhrqx2h40000gn/T/pip-install-zbfuwsf7/hdt/
  Complete output (45 lines):
  /usr/local/anaconda3/lib/python3.7/site-packages/setuptools/dist.py:724: UserWarning: Module pybind11 was already imported from /usr/local/anaconda3/lib/python3.7/site-packages/pybind11/__init__.py, but /private/var/folders/dc/dd3sxplx0h97kmd_xhrqx2h40000gn/T/pip-install-zbfuwsf7/hdt/.eggs/pybind11-2.2.4-py3.7.egg is being added to sys.path
    pkg_resources.working_set.add(dist, replace=True)
```

**Comment by PhilippChr** [comment]
Hi,
unfortunately it is quite hard for me to help you with this. It seems that there already is some version of pybind11 installed, which is not compatible with hdt.
I think that uninstalling pybind11 or creating a new virtual environment using conda could help here.
Regards,
Philipp

**Comment by jingjing-unilu** [comment]
Hi,
Many thanks for the quick reply and I'm trying now.
Best Regards,

**Comment by jingjing-unilu** [comment]
Hi, 
I have tried **conda virtual environment**, following [https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/](url). I use `python=3.7` in here. 
Besides, I use 
`pip install --no-cache-dir pybind11`, 
`pip install --no-cache-dir spacy`, 
`pip install --no-cache-dir requests`,  
`pip install --no-cache-dir hdt`, 
`pip install --no-cache-dir networkx`, 
`python -m spacy download en_vectors_web_lg` 
one by one. It works now.

However, I have test the **conda virtual environment** using `python=2.7`. 
It doesn't work when I use `pip install --no-cache-dir hdt`. After checking the document, I find the `hdt `needs **Python version 3.6.4 or higher**, please check it in [https://pypi.org/project/hdt/](url).

Best Regards,

**Comment by PhilippChr** [comment]
Hi,
I have it running with Python 2.7 on my machine. There are several release versions of hdt. If you want to use Python 2.7, please try out this version https://pypi.org/project/hdt/2.0/.
Regards,
Philipp

**Comment by jingjing-unilu** [comment]
> Hi,
> I have it running with Python 2.7 on my machine. There are several release versions of hdt. If you want to use Python 2.7, please try out this version https://pypi.org/project/hdt/2.0/.
> Regards,
> Philipp

Hi,
Got it, many thanks for reply. I will try it then.
Best regards,

**Comment by PhilippChr** [comment]
I guess I can close the issue then 👍
