### ISSUE TITLE
Custom knowledge graph

### ISSUE THREAD

**Issue by Sharathmk99** [PhilippChr/CONVEX#8]
Hi,

We have custom knowledge graph built. How can I use this repository on my custom knowledge graph. Currently we have saved our graph in Neo4j

**Comment by PhilippChr** [comment]
Hi,
to use a Neo4j graph, you would need to reimplement the functions in library/wikidata.py.
You need to stick to the output formats of these functions, to get the code working,
e.g. return the same dictionary-format as a statement in the get_all_statements_of_entity-function.
