### ISSUE TITLE
The existentials question

### ISSUE THREAD

**Issue by 2213500360** [PhilippChr/CONVEX#9]
Hello,After reading your paper and coding, I have a question. There are many existentials questions in your dataset, such as "Is the rain song and immigrant song there?",so How did you get the answer to this kind of questions?
I found the following code in your coding.
ranked_answers = [{'answer': "yes", 'answer_score': 1.0, 'rank': 1}, {'answer': "no", 'answer_score': 0.5, 'rank': 2}]
 I didn't understand it. Could you explain it？thinks.

**Comment by PhilippChr** [comment]
Hello,
thanks for your interest in our work!
In our methodology, we do not have an explicit mechanism for handling existential questions.
Therefore, we identify existential questions using keywords, and return "Yes" as the default answer.
Still, existential questions are valid questions in a conversation, and occurred naturally in our user study.
We hope that in future research, methods for dealing with existential questions are developed, which would
ultimately improve the performance by quite some margin.

**Comment by 2213500360** [comment]
Thank you for your explanation, but I have another question. How do you solve the quantity questions like "how many"?

**Comment by PhilippChr** [comment]
CONVEX uses Wikidata as information source, and Wikidata has such information for many entities.
E.g. the Game of Thrones (https://www.wikidata.org/wiki/Q23572) entity has the information:
Game of Thrones - number of seasons - 8

So such questions are treated in the standard way outlined in the paper.

**Comment by 2213500360** [comment]
Thank you for answer!
